Add link from citation in Slack to log
vim-jp/slacklog-generator pull request #164
Opened 2021-05-23 05:07 UTC by kato-k

![image](https://user-images.githubusercontent.com/45391880/119248996-2bf4fe80-bbd0-11eb-9da7-83e3e4297b73.png)

2021-05-23 05:09 UTC, kato-k commented
TODO
- [ ] タイムゾーン
- [ ] リプライについた引用

2021-05-23 05:27 UTC, thinca reviewed
Go わからないなりに見ました 👀

2021-05-23 05:27 UTC, thinca commented on templates/channel_per_month/attachment.tmpl
> +        <a href="{{ genAttachedURL .Ts .FromURL }}" target="_blank" rel="noopener noreferrer">slacklog</a>
`{{ $.baseURL }}` が必要そうです。

2021-05-23 05:27 UTC, thinca commented on internal/slacklog/generator.go
> +				}
そのまま return するほうが個人的にはわかりやすくて好みだけど、どちらが Go ぽいかはわからぬ…。
(好みの範疇だと思うのでどちらでもよいです)

```suggestion
				return len(fromURL) >= 25 && fromURL[0:25] == "https://vim-jp.slack.com/"
```

2021-05-23 09:33 UTC, kato-k commented on templates/channel_per_month/attachment.tmpl
> +        <a href="{{ genAttachedURL .Ts .FromURL }}" target="_blank" rel="noopener noreferrer">slacklog</a>
$.baseURLをattachment.tmplから参照できそうになかったので、
重複してしまうのですが、baseURLを返すメソッドを追加しました

2021-05-23 11:44 UTC, raa0121 requested changes

2021-05-23 11:44 UTC, raa0121 commented on internal/slacklog/generator.go
> +      "getBaseURL": func() string {
インデント、揃ってないですね

2021-05-23 12:47 UTC, kato-k commented on internal/slacklog/generator.go
> +      "getBaseURL": func() string {
ありがとうございます！修正しました！
(タブインデントだったことを忘れてました)

2021-05-24 15:37 UTC, kato-k commented
よく見たらTsToDateTime()が生えていたのでそちらを使って時間計算をしました。
タイムゾーンに関する問題は修正できたかと思います。

2021-05-24 15:47 UTC, thinca commented on internal/slacklog/generator.go
> +				unixTime := TsToDateTime(timestamp)
これは `time.Time` なので `unixTime` ではなさそうです。

2021-05-25 13:17 UTC, kato-k reviewed
良い変数名が思いつかなかったのであれですが、修正しました
ありがとうございます

2021-05-25 15:21 UTC, thinca approved these changes

2021-05-25 15:22 UTC, raa0121 approved these changes

2021-05-25 15:24 UTC, merged